# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.100.78:3306/trustchain?characterEncoding=UTF-8&allowMultiQueries=true
    #    username: root
    #    password: Beihang2022!
    url: jdbc:mysql://localhost:3306/trustchain?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 258667
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:log4j2.xml

server:
  servlet:
    session:
      timeout: 3600s

minio:
  endpoint: http://127.0.0.1:9000
  bucket: trustchain
  accessKey: 3wIc88pusSVNraoT1qrV
  secretKey: jOc02HsuPdJsiFZGdhXx8gdROyN3dunF5zyBPPiV
